print('Benvenuto nel mio programma per generare nomi curiosi di band')
print('Dove sei nato?')
luogo_nascita=input()
print('E come si chiama il tuo animale domestico?')
nomeanimale=input()
print ((('Perfetto allora il nome della tua band potrebbe essere ')+str(luogo_nascita)+str(nomeanimale)))