print('Benvenuto carissimo')
print('Volevo farti due domandine')
print('Dove sei nato?')
luogo_nascita=input()
print (('Ah vieni da ') + str( luogo_nascita))
print('E come si chiama il tuo animale domestico?')
nomeanimale=input()
print (('ah il tuo animale si chiama')+str(nomeanimale))
print ((('Perfetto allora il nome della tua band può essere ')+str(luogo_nascita)+str(nomeanimale)))